# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-943f35e2-2292-4414-be4f-eee7037713d6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-943f35e2-2292-4414-be4f-eee7037713d6" =
    { device = "/dev/disk/by-uuid/943f35e2-2292-4414-be4f-eee7037713d6";
      crypttabExtraOpts = [ "tpm2-device=auto" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2451-5D67";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
