-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Bibata-Material-Lilac")
hl.env("XCURSOR_THEME", "Bibata-Material-Lilac")
hl.env("HYPRCURSOR_SIZE", "30")
hl.env("XCURSOR_SIZE", "30")
